---
title: "Resources"
output: html_document
---

### R and R-Studio

[R](http://www.r-project.org) is a free open-source programming language that can be used for statistical analysis, data-simulation, graphing, and lots of other stuff. Another free program is [R-studio](http://www.rstudio.com), that provides a nice graphic interface for R. Download R first, then download R-studio. Both can run on PCs, Macs or Linux. Students will be learning R in the stats labs using the lab manual [lab manual](https://crumplab.github.io/statisticsLab/).

### Additional R resources


1. Google is great, Google your problem
2. [Stackoverflow](https://stackoverflow.com) is great, Google will often take you there because someone has already asked your question, and someone else has answered, usually many people have answered your question many ways.
3. Danielle Navarro wrote a [free Psych Stats textbook using R](https://compcogscisydney.org/learning-statistics-with-r/), it's worth checking out (some of our textbook are based on Danielle's)
4. Danielle Navarro recently made this website for introducing R, it's great, check it out (also made using this R markdown process): [http://compcogscisydney.org/psyr/](http://compcogscisydney.org/psyr/)
5. Check out my slightly older programming book that also introduces R [https://crumplab.github.io/programmingforpsych/](https://crumplab.github.io/programmingforpsych/)
6. Another solid and accessible resource for psyc stats using R [https://ademos.people.uic.edu/index.html](https://ademos.people.uic.edu/index.html).

### R basics lab

This is the lab for week 3, where we talk about some basic things when using R and R studio. The link to the lab is [http://crumplab.github.io/psyc3400/lab3_rbasics/RBasics.html](http://crumplab.github.io/psyc3400/lab3_rbasics/RBasics.html).

**IMPORTANT**: If you are in a thursday lab you will complete this lab in class on Thursday, September 13th 2018. If you are in a Tuesday lab, then you will complete this lab on your own time before your next lab (Tuesday, September 25th).

