---
title: "Syllabus"
output: 
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 3
---

**this is copied from a previous course, needs to be updated, using for example syllabus**

Statistical Methods in Psychological Research (PSYC3400) Sections: TBD

Lectures 	
- Monday	12:25PM-2:05PM 	RM: Ingersoll 1310

Instructor

- Dr. Matt Crump	4307B James Hall
- Office hours:	by appointment
- Office phone: 718-951-5000 x. 6068
- mcrump@brooklyn.cuny.edu

### Labs and Lab Instructors

| Section| Day | Time| Room| Instructor| email|
|:--------|:-------:|:--------|:--------|:--------|:--------|
|MTAB 17771| 	M | 2:15p-5:50p |	WJ3106 |Beliz Hazan	|belizhazanlab@gmail.com|
|MTBB 17773| 	M | 2:15p-5:50p	|WJ4109|Nicholaus Brosowsky|nbrosowsky@gradcenter.cuny.edu|
|MTCB 17775| 	W   | 12:25-4:00p| WJ3106| Taylan Ergun	|	taylansergun@gmail.com |
|MTDB 17777| 	W  | 12:25p-4:00p|  WJ4109 |	Alexandra Gaynor|alexandra.gaynor@gmail.com|
|MTEB 53895| 	F  | 9:05a-12:40p| WJ-3106  |Matthew Goldberg	|matt.goldberg100@gmail.com |
|MTFB 53897| 	F  | 9:05a-12:40p|  WJ-4109 |	Beliz Hazan|belizhazanlab@gmail.com|



### Lecture Schedule

```{r, message=FALSE, warning=FALSE, echo=FALSE}
library(data.table)
schedule<-fread("Schedule.csv")
knitr::kable(schedule)

```



Website:  [http://crumplab.github.io/courses/experimental](http://crumplab.github.io/courses/experimental)

### Catalog Description

2 hours lecture, 4 hours laboratory, 4 credits

Basic principles of experimental psychology and experimental methodology. A variety of specific content areas in psychology, including those in social psychology, learning, perception, and cognitive psychology. Laboratory replication of classic experiments from these content areas. Writing intensive course

### Course Objectives

My goal is for you to learn:

1. To read and evaluate psychological literature
2. The basics of scientific methodology in psychology. This will be achieved by working through most of the important steps involved in conducting experimental research
3. How research benefits from being conducted as part of a research team and in the context of a critical community of peers
4.	Whether you may be interested in other courses and programs that involve empirical research
5.	To evaluate claims like those presented in the media (e.g., do video games improve your attention, etc.), and understand the differences between science and pseudoscience

NOTE: The schedule and procedures described in this syllabus are subject to change in the event of extenuating circumstances. You will always be notified of changes both in class AND by posts to the class website. Your enrollment in the course represents your acknowledgment and acceptance of the non-negotiable policies described in the syllabus.

### Textbook. Required:

The textbook for this course is FREE and downloadable as a .pdf. See the main page for the download link.

UPDATE


### Important dates

|Date| Event|
|:--|:--|
|Thursday, August 31|Last day to add a course|
|Thursday, September 14| Last day to drop a course without a grade of "W"|
|Friday, September 15 |Last day to apply for Fall 2017 Graduation|
|Thursday, November 9| Last day to resolve Spring and Summer 2017 incomplete grade (INC)|
|Friday, November 10| Last day to withdraw from a course with a W (non-penalty) grade|

### Lab Schedule		

|Lecture|	Date|
|:--|:--|
|1|	Lab Overview		|
|2|	Paper Project 1: Fluency|
|3|	Paper Project 1: Continued|		
|4|	Adaptive memory	|
|5|	Task-Switching	|
|6|	Stroop		|
|7|	Paper Project 2: Face-Inversion	|
|8|	Paper Project 2 continued		|
|9|	Brainstorm Individual projects|
|10|	Individual presentations	|
|11|	Group work Final Project	|
|12|	Group work Final Project	|
|13|	Group work Final Project	|
|14|	Final Presentations	|


### Additional resources

Supplementary material will be posted on the course website. Lab instructors may recommend a text that specifically outlines the APA format and writing APA style research reports. This course will require use of the web, internet tools, and open-source (free) computing tools available in the lab.

### Course Structure:

#### The Lecture

There will be a two hour lecture each week. The lecture covers material that is available in the text book. The course schedule outlines chapters that should be read prior to each lecture. Some lectures will require reading of supplementary material, and access to these materials will be posted online using the course website. The lectures will also cover material that is thematically related to that presented in the textbook. The purpose of the lecture is to cover important concepts in experimental psychology, and prepare you for conducting psychological research in the laboratory. You will be tested on material from the lectures and textbook in two exams: a midterm, and a cumulative final exam.

#### The Lab

There will be a four hour lab each week. Details on the lab component will be made available by your lab instructor. All sections will complete several lab projects, and three lab papers. Each lab paper involves writing a full APA research report. The first two papers are predetermined, and will cover classic experimental procedures. The third lab paper is to create, conduct, and report your own research project. The third lab paper will require two separate in-class presentations, the first is an individual five minute presentation, and the second is a ten minute group presentation. The third lab paper also requires that each individual submit a complete, and independently written research report. The details of each lab assignment will be made available to you through the lab syllabus, as well as online through the course website.  

### Grading (total of 100)

Your final grade combines your performance in the lab and lecture portions of the course. The percentage grade is determined from the following components.

||||
|:--|:--|:--|
|						||Total %|
|Lecture|||
||Assignments & Attendance (lab and lecture)	|		20%|
||Midterm 				|	10%|
||Final exam (cumulative) 		|	25%|
||Extra Credit				|	up to 2% (see below)|
|Lab||
||Paper 1 				|	10%|
||Paper 2 				|10%|
||Paper 3 				|	15%|
||Presentation 1 	|			5%|
||Presentation 2  |				5%|

Percentage grades are converted to letter grades according to the following rubric.

|Letter grade|Range|
|:--|:--|
|F	|0-59.99|
|D-	|60-63.32|
|D	|63.33-66.66|
|D+	|66.67-69.99|
|C-	|70-72.99|
|C	|73-76.66|
|C+	|76.67-79.49|
|B-	|79.5-83.32|
|B	|83.33-86.66|
|B+	|86.67-89.99|
|A-	|90-93.32|
|A	|93.33-96.66|
|A+	|96.67-100|

The course allows for some flexibility in determining your final grade. If you perform better on the final exam than on the midterm, you may replace the midterm grade with your higher final grade (the reverse does not apply).  The major focus of this course is to develop your writing abilities. As writing in the APA format may be unfamiliar to some, the course allows that, IF you complete all 3 papers, then, you will have the opportunity to replace your lowest paper grade from paper 1 or paper 2, with your highest grade from paper 1 or 2. The instructor reserves the right to determine whether the final grade depends more heavily on a scale or a curve.

### Lecture and Lab Assignments and Attendance



The lecture portion will involve weekly assignments that are to be completed electronically on blackboard. Assignments are usually short quizzes (10-20 questions). “Assignments & Attendance” accounts for 20% of the final grade. The 20% is computed from the assignments, but can be decreased as a result of poor attendance. If a student is late or misses more than 3 classes, then each additional late/missed class will result in subtracting 1% from the 20% for Assignments and Attendance.

Lecture attendance is taken every lecture at the very beginning of class. Latecomers who miss attendance will not be allowed to record their attendance, and will be recorded as absent.

The lab portion will involve weekly assignments completed in the lab. Attendance will also be taken in the lab each week. It is absolutely critical that you arrive to labs on time. If you do not arrive on time you will be given a late. If you are late or miss a lab more than three times, then you will be penalized for each additional lateness or absence by 1% of from the 20% for Assignments and Attendance.

If you do have to miss class due to exceptional circumstances, please make arrangements to get notes from a classmate

### Extra credit

You have the opportunity to gain extra credit in this course by participating in experiments that are offered through the online sign-up system [http://brooklyncollege.sona-systems.com/](http://brooklyncollege.sona-systems.com/)
You must give yourself a new user name, and select this course. For every hour of participation you will receive 1% extra credit, to a max of 2%.  The system will automatically record your credit. If you wish to receive extra credit without participating, ask me about other writing assignment options.

### University’s policy on Academic Integrity

The faculty and administration of Brooklyn College support an environment free from cheating and plagiarism. As a student, you are personally responsible for being aware of what constitutes cheating, and plagiarism; and, for avoiding both. You can view the complete text of the CUNY Academic Integrity Policy here:
[http://www.brooklyn.cuny.edu/bc/policies](http://www.brooklyn.cuny.edu/bc/policies)
If a faculty member suspects a violation of academic integrity, and upon investigation, confirms that violation, or if the student admits the violation, the faculty member MUST report the violation.

### Missing an Exam or class

Make-up exams will be given only when there is a “good” reason for having missed an exam. For example, if a sudden illness causes you to miss an exam, then you should be prepared to provide me with a brief note signed by your physician. Contact me before an exam in the event that you anticipate missing one. In the event of an emergency, contact me as soon as possible. If you are missing a class for religious reasons refer to the state law regarding non-attendance because of religious beliefs (p. 64 in the Undergraduate Bulletin or p. 40 of the Graduate Bulletin).

WARNING: This is not the kind of course for which you do not need to come to class, and read the textbook at the last minute and expect to do well on tests and papers. The material in this course builds in complexity across classes, and doing well in this course will require a constant moderate level of effort. If you join the course later or are unsure about anything please ask.

### Accessibility

It is important to me that the course be accessible to all students. In order to receive disability-related academic accommodations students must first be registered with the Center for Student Disability Services. Students who have a documented disability or suspect they may have a disability are invited to set up an appointment with the Director of the Center for Student Disability Services, Ms. Valerie Stewart-Lovell at 718-951-5538. If you have already registered with the Center for Student Disability Services please provide me with the course accommodation form so we may discuss your specific accommodation. A guide and more information can be found here [http://catsweb.cuny.edu](http://catsweb.cuny.edu)

#### Class Citizenship/Rules of Conduct

#### Cell phones

Your cell phone, PDA or other device must be turned off during class. If you are a habitual offender in this respect (i.e. it happens more than twice during the semester), you will be asked to leave the classroom. If you absolutely need to have your phone on during class—talk to me at the beginning of the semester.

#### Keep the room clean

Please pick up after yourself. Absolutely no food is allowed in the lecture and lab rooms.

#### Email Correspondence

I will regularly use e-mail to send out announcements, changes in the syllabus, reminders about tests or due dates etc. It is your responsibility to check e-mail regularly to keep up-to-date with these announcements. I will use the e-mail address you have listed with the College. Therefore, please make sure that this is indeed the correct address.

#### General Help with Research and Writing

The Library maintains a collection of links to sites that can assist you with proper citation format and paraphrasing and quoting other authors at [Research & Writing Help](https://library.brooklyn.cuny.edu/resources/?service=research-help).  The Learning Center has writing tutors available to help you with your writing [http://lc.brooklyn.cuny.edu/](http://lc.brooklyn.cuny.edu/).

The best learning is done in conversation with others, whether they are people—classmates, teachers, friends—or texts—books, articles, essays, poems, films etc. It should not be a solitary process. However, the assignments that you hand in for this course must be done on your own, should represent your own thinking, and should be original work that you have done for this particular course. A good way to balance these two seemingly contradictory approaches (collaborative learning and original individually-produced work) without knowingly—or, even unwittingly—resorting to plagiarism or other forms of academic misconduct is to learn and meticulously observe the rules for citing the work of others (this could be the great point your roommate made that you used in your paper, it could be a well-turned phrase from an academic essay, or it could be anything in between). It is your responsibility to learn what constitutes plagiarism and the correct rules for citing sources—read the information on the following website carefully: [http://www.brooklyn.cuny.edu/bc/policies/](http://www.brooklyn.cuny.edu/bc/policies/). The bottom line is: passing off anyone’s words or ideas as your own for any reason whatsoever is plagiarism.
